import { IBM_Plex_Sans_Thai } from 'next/font/google'

import type { Metadata } from 'next'

import './globals.css'
import QueryProviders from '@/providers/query-provider'

const IBMPlexSansThai = IBM_Plex_Sans_Thai({
  weight: ['400', '700'],
  subsets: ['latin', 'thai'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang='en'>
      <body className={`${IBMPlexSansThai.className} antialiased`}>
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  )
}

export default RootLayout
